téléchargement de la dataset fusionnée

In [10]:
import pandas as pd

df = pd.read_csv("cpu_full_dataset.csv")
df.head()

             timestamp  value serveur_id
0  2014-02-14 14:30:00  0.132     24ae8d
1  2014-02-14 14:35:00  0.134     24ae8d
2  2014-02-14 14:40:00  0.134     24ae8d
3  2014-02-14 14:45:00  0.134     24ae8d
4  2014-02-14 14:50:00  0.134     24ae8d

Exercice A : indexation 
Transformation de la colonne timestamp en format datetime et de la définir comme index du DataFrame afin de pouvoir utiliser les fonctionnalités spécifiques aux séries temporelles

In [11]:

df['timestamp'] = pd.to_datetime(df['timestamp'])
df = df.sort_values(by=['serveur_id', 'timestamp'])
df = df.set_index('timestamp')
df.head()

                     value serveur_id
timestamp
2014-02-14 14:30:00  0.132     24ae8d
2014-02-14 14:35:00  0.134     24ae8d
2014-02-14 14:40:00  0.134     24ae8d
2014-02-14 14:45:00  0.134     24ae8d
2014-02-14 14:50:00  0.134     24ae8d

Resampling
Regroupement des données par heure et calcul de la moyenne d'utilisation du cpu par heure afin d'obtenir une vision plus globale

In [12]:
df_hourly = (df.groupby('serveur_id')['value'].resample('h').mean())
df_hourly.head()

serveur_id  timestamp
24ae8d      2014-02-14 14:00:00    0.133667
            2014-02-14 15:00:00    0.122333
            2014-02-14 16:00:00    0.122667
            2014-02-14 17:00:00    0.133667
            2014-02-14 18:00:00    0.128333
Name: value, dtype: float64

Rolling Window
Calcul de la moyenne mobile des 5 derniéres observations afin de mieux observer la tendances d'utilisation du cpu

In [18]:
df['moyenne_mobile_5'] = df.groupby('serveur_id')['value'].transform(lambda x: x.rolling(5).mean())
df.head(15)

                     value serveur_id  moyenne_mobile_5  target
timestamp
2014-02-14 14:30:00  0.132     24ae8d               NaN   0.134
2014-02-14 14:35:00  0.134     24ae8d               NaN   0.134
2014-02-14 14:40:00  0.134     24ae8d               NaN   0.134
2014-02-14 14:45:00  0.134     24ae8d               NaN   0.134
2014-02-14 14:50:00  0.134     24ae8d            0.1336   0.134
2014-02-14 14:55:00  0.134     24ae8d            0.1340   0.134
2014-02-14 15:00:00  0.134     24ae8d            0.1340   0.134
2014-02-14 15:05:00  0.134     24ae8d            0.1340   0.066
2014-02-14 15:10:00  0.066     24ae8d            0.1204   0.132
2014-02-14 15:15:00  0.132     24ae8d            0.1200   0.134
2014-02-14 15:20:00  0.134     24ae8d            0.1200   0.066
2014-02-14 15:25:00  0.066     24ae8d            0.1064   0.132
2014-02-14 15:30:00  0.132     24ae8d            0.1060   0.202
2014-02-14 15:35:00  0.202     24ae8d            0.1332   0.068
2014-02-14 15:40:00  0.068     24ae8d            0.1204   0.134

Lagging
Création  d'une variable cible correspondant à la valeur future du CPU, afin de transformer la série temporelle en problème de régression supervisée pour la modélisation prédictive.

In [ ]:
df['target'] = df.groupby('serveur_id')['value'].shift(-1)
df.head(15)

                     value serveur_id  moyenne_mobile_5  target
timestamp
2014-02-14 14:30:00  0.132     24ae8d               NaN   0.134
2014-02-14 14:35:00  0.134     24ae8d               NaN   0.134
2014-02-14 14:40:00  0.134     24ae8d               NaN   0.134
2014-02-14 14:45:00  0.134     24ae8d               NaN   0.134
2014-02-14 14:50:00  0.134     24ae8d            0.1336   0.134
...                    ...        ...               ...     ...
2014-02-17 22:45:00  1.762     53ea38            1.8388   1.734
2014-02-17 22:50:00  1.734     53ea38            1.8196   1.766
2014-02-17 22:55:00  1.766     53ea38            1.8196   1.800
2014-02-17 23:00:00  1.800     53ea38            1.8008   1.834
2014-02-17 23:05:00  1.834     53ea38            1.7792   1.992

[5000 rows x 4 columns]

Nettoyage final

In [21]:
df=df.dropna()
df.head(15)

                     value serveur_id  moyenne_mobile_5  target
timestamp
2014-02-14 14:50:00  0.134     24ae8d            0.1336   0.134
2014-02-14 14:55:00  0.134     24ae8d            0.1340   0.134
2014-02-14 15:00:00  0.134     24ae8d            0.1340   0.134
2014-02-14 15:05:00  0.134     24ae8d            0.1340   0.066
2014-02-14 15:10:00  0.066     24ae8d            0.1204   0.132
2014-02-14 15:15:00  0.132     24ae8d            0.1200   0.134
2014-02-14 15:20:00  0.134     24ae8d            0.1200   0.066
2014-02-14 15:25:00  0.066     24ae8d            0.1064   0.132
2014-02-14 15:30:00  0.132     24ae8d            0.1060   0.202
2014-02-14 15:35:00  0.202     24ae8d            0.1332   0.068
2014-02-14 15:40:00  0.068     24ae8d            0.1204   0.134
2014-02-14 15:45:00  0.134     24ae8d            0.1204   0.132
2014-02-14 15:50:00  0.132     24ae8d            0.1336   0.134
2014-02-14 15:55:00  0.134     24ae8d            0.1340   0.134
2014-02-14 16:00:00  0.134     24ae8d            0.1204   0.136